# Generated by Django 3.2.5 on 2021-07-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210722_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstragramPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='menu/instragram', verbose_name='Фото')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Фото из Instagram',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='menu/testimonials', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
