# Generated by Django 3.2.5 on 2021-07-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_instragramphoto_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото галлереи',
                'verbose_name_plural': 'Фото галлереи',
            },
        ),
        migrations.AlterModelOptions(
            name='instragramphoto',
            options={'verbose_name': 'Фото из Instagram', 'verbose_name_plural': 'Фото из Instagram'},
        ),
        migrations.AlterField(
            model_name='combomenu',
            name='photo',
            field=models.ImageField(upload_to='menu/combo_menu', verbose_name='Фото'),
        ),
    ]
