# Generated by Django 3.2.5 on 2021-07-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_photogallery_css_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='css_style',
            field=models.CharField(choices=[('small_img', 'Small'), ('big_img', 'Big')], default='Small', max_length=255, verbose_name='Стиль CSS'),
        ),
    ]
