# Generated by Django 3.2.5 on 2021-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_photogallery_css_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoOnIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Ссылка на видео')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Видео на главной',
                'verbose_name_plural': 'Видео на главной',
            },
        ),
    ]
